"""baseline

Revision ID: 08301d725404
Revises: 
Create Date: 2026-08-06 16:41:11.855217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08301d725404'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clients_ghl_contact_id_key'), 'clients', type_='unique')
    op.create_index(op.f('ix_clients_ghl_contact_id'), 'clients', ['ghl_contact_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_ghl_contact_id'), table_name='clients')
    op.create_unique_constraint(op.f('clients_ghl_contact_id_key'), 'clients', ['ghl_contact_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
